# Generated by Django 5.0.6 on 2026-04-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubarr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed', to='youtubarr.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'video_id')},
            },
        ),
    ]
