# Generated by Django 5.0.6 on 2026-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubarr', '0002_dismisseditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitem',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DismissedItem',
        ),
    ]
